require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'
$RNFirebaseAsStaticFramework = true

platform :ios, '14.0'
install! 'cocoapods', :deterministic_uuids => false

target 'TrendTaxi' do
  # use_frameworks!
  
  config = use_native_modules!

  # Flags change depending on the env values.
  flags = get_default_flags()

  use_react_native!(
    :path => config[:reactNativePath],
    # to enable hermes on iOS, change `false` to `true` and then install pods
    :hermes_enabled => flags[:hermes_enabled],
    :fabric_enabled => flags[:fabric_enabled],
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )
  rn_maps_path = '../node_modules/react-native-maps'
  pod 'react-native-google-maps', :path => rn_maps_path
  pod 'react-native-maps', path: rn_maps_path
  pod 'react-native-geolocation', :path => '../node_modules/@react-native-community/geolocation'
  pod 'GoogleMaps'
pod 'Google-Maps-iOS-Utils'


  pod 'react-native-keep-awake', :path => '../node_modules/react-native-keep-awake'

  pod 'RNSound', :path => '../node_modules/react-native-sound'

  target 'TrendTaxiTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable the next line.
  use_flipper!()

  post_install do |installer|
    react_native_post_install(installer)
    __apply_Xcode_12_5_M1_post_install_workaround(installer)
  end
end
