
# Override Firebase SDK Version
$RNFirebaseAsStaticFramework = true
# $FirebaseSDKVersion = '15.7.0'

platform :ios, '14'

require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

# source cocoapods
install! 'cocoapods', :deterministic_uuids => false


target 'TrendTaxi' do
  $static_framework = []
  rn_maps_path = '../node_modules/react-native-maps'

  config = use_native_modules!
  flags = get_default_flags()

  use_react_native!(
    :path => config[:reactNativePath],
    # to enable hermes on iOS, change `false` to `true` and then install pods
    :hermes_enabled => flags[:hermes_enabled],
    :fabric_enabled => flags[:fabric_enabled],
    # An absolute path to your application root.
    # :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  $static_framework += [
    'react-native-maps',
    'react-native-google-maps',
    'Google-Maps-iOS-Utils',
    'GoogleMaps',
  ]

  pod 'react-native-google-maps', :path => rn_maps_path
  pod 'GoogleMaps'
  pod 'Google-Maps-iOS-Utils'
  pod 'react-native-keep-awake', :path => '../node_modules/react-native-keep-awake'
  pod 'react-native-geolocation', :path => '../node_modules/@react-native-community/geolocation'
  pod 'RNSound', :path => '../node_modules/react-native-sound'

  use_frameworks! :linkage => :static

  target 'TrendTaxiTests' do
    inherit! :complete
    # Pods for testing
  end
  
  
  
   post_install do |installer|
      
      installer.pods_project.targets.each do |target|
        if target.name == 'RCT-Folly'
            target.build_configurations.each do |config|
                config.build_settings['HEADER_SEARCH_PATHS'] = "$(inherited) ${PODS_ROOT}/fmt/include"
            end
        end
  
        if target.name == 'react-native-google-maps'
          target.build_configurations.each do |config|
            config.build_settings['CLANG_ENABLE_MODULES'] = 'No'
          end
        end
      end
      react_native_post_install(installer)
      __apply_Xcode_12_5_M1_post_install_workaround(installer)
      installer.pods_project.build_configurations.each do |config|
        config.build_settings["EXCLUDED_ARCHS[sdk=iphonesimulator*]"] = "arm64"
      end
    end
  
  
end

  